language: python
python:
    - '3.3'
    - '3.4'

install:
    - pip install -r travis.pip --use-mirrors

script:
    - cd socbook
    - python manage.py migrate
    - coverage run --source='.' manage.py test

after_success:
    - coveralls --rcfile=.coverage.rcfile

