language: python
python:
    - '3.4'

install:
    - pip install -r requirements/travis.pip

script:
    - cd socbook
    - python manage.py migrate
    - coverage run --source='.' manage.py test

after_success:
    - coveralls --rcfile=.coverage.rcfile

